basedata = {
    'dchordtype':{
        'major':['',0,4,7],
        'minor':['m',0,3,7],
        'major7th':['maj7',0,4,7,11],
        'minor7th':['m7',0,3,7,10],
        'dominant7th':['7',0,4,7,10]
        },
    'dscaletype':{
        'majscale':{
            'scalenotes':[0,2,4,5,7,9,11],
            'ctypeofscale':[]
            },
        'minscale':{
            'scalenotes':[0,2,3,5,7,8,10],
            'ctypeofscale':[]
            }
        }
    }